[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "quadratic_map_attractor"
version = "0.1.0"
requires-python = ">=3.8"
dependencies = [
    "maturin>=1.12.4",
    "numpy>=1.24.4",
]
